// <auto-generated />
namespace SpadStorePanel.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CommentShortTitleAndTechnicalSpecifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentShortTitleAndTechnicalSpecifications));
        
        string IMigrationMetadata.Id
        {
            get { return "202107131058581_CommentShortTitleAndTechnicalSpecifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
